spring:
  application:
    name: komersa

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true


swagger:
  documentation:
    uri: uri

    # TODO: springdoc -> yaml config
#springdoc:
 # api-docs:
  #  enabled: true
   # path: docs/openapi.yaml
 # swagger-ui:
  #  enabled: true
   # urls:
    #  - url: docs/openapi.yaml
